"use strict";

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const STORE = path.join(__dirname, "public_reports.json");
const MAX_REPORTS = 200;

const ATTRIBUTION_LINE =
  "This plan was generated by AETHRA — an autonomous business operator.";

const REFERRAL_UNLOCK_THRESHOLD = 3;

function getPublicBase() {
  return String(process.env.AETHRA_PUBLIC_BASE_URL || "http://localhost:4000").replace(/\/$/, "");
}

function getShareBase() {
  const s = process.env.AETHRA_SHARE_BASE || process.env.AETHRA_PUBLIC_BASE_URL || "http://localhost:4000";
  return String(s).replace(/\/$/, "");
}

function generateRunId() {
  return `r_${Date.now().toString(36)}_${crypto.randomBytes(6).toString("hex")}`;
}

function generateShareLink(runId) {
  const base = getShareBase();
  return `${base}/report.html?id=${encodeURIComponent(runId)}`;
}

function referralUnlockMessage(referrals) {
  const n = Number(referrals) || 0;
  if (n >= REFERRAL_UNLOCK_THRESHOLD) {
    return {
      unlocked: true,
      benefit: "extra runs",
      detail: "Referral threshold met — bonus run allowance applied on next cycle.",
    };
  }
  const need = Math.max(0, REFERRAL_UNLOCK_THRESHOLD - n);
  return {
    unlocked: false,
    benefit: null,
    detail: `${need} more referral(s) unlock extra runs.`,
  };
}

function anonymiseReportPayload(envelope) {
  const d = envelope && envelope.decision ? envelope.decision : {};
  const strat = envelope && envelope.strategy && typeof envelope.strategy === "object" ? envelope.strategy : {};
  return {
    verdict: d.verdict != null ? String(d.verdict) : null,
    confidence: d.confidence_0_100 != null ? d.confidence_0_100 : d.confidence,
    scores: d.scores && typeof d.scores === "object" ? { ...d.scores } : null,
    thesis_line: strat.one_line != null ? String(strat.one_line).slice(0, 200) : null,
    ideas_preview: Array.isArray(envelope?.ideas_layer?.suggestions)
      ? envelope.ideas_layer.suggestions.slice(0, 3).map((x) => ({
          idea: String(x.idea || "").slice(0, 120),
          score: x.score,
        }))
      : [],
    recorded_at: Date.now(),
  };
}

function loadStore() {
  try {
    const j = JSON.parse(fs.readFileSync(STORE, "utf8"));
    return Array.isArray(j.reports) ? j : { reports: [] };
  } catch {
    return { reports: [] };
  }
}

function saveReport(runId, payload) {
  const id = String(runId || "").slice(0, 80);
  if (!id) return;
  const st = loadStore();
  const row = { id, payload, saved_at: Date.now() };
  st.reports.unshift(row);
  while (st.reports.length > MAX_REPORTS) st.reports.pop();
  try {
    fs.writeFileSync(STORE, JSON.stringify(st, null, 2), "utf8");
  } catch {
    /* non-fatal */
  }
}

function getPublicReport(runId) {
  const id = String(runId || "");
  const st = loadStore();
  const hit = (st.reports || []).find((r) => r.id === id);
  return hit ? hit.payload : null;
}

function buildViralLayer(runId, options = {}) {
  const referrals = Number(options.referrals) || 0;
  const ref = referralUnlockMessage(referrals);
  const idEnc = encodeURIComponent(String(runId || ""));

  return {
    run_id: runId,
    share_url: generateShareLink(runId),
    canonical_share_url: `https://aethra.ai/report/${idEnc}`,
    attribution_line: ATTRIBUTION_LINE,
    public_results_page: `${getPublicBase()}/report.html`,
    referral: ref,
  };
}

module.exports = {
  ATTRIBUTION_LINE,
  generateRunId,
  generateShareLink,
  referralUnlockMessage,
  anonymiseReportPayload,
  saveReport,
  getPublicReport,
  buildViralLayer,
  REFERRAL_UNLOCK_THRESHOLD,
};
